### ISSUE TITLE
occur vel  jump seriously  by test，so Can you improve it and solve the problem

### ISSUE THREAD

**Issue by dbdxnuliba** [severin-lemaignan/softMotion-libs#1]
**build/src$ ./svg2traj ../../sample/horse.svg**

![image](https://user-images.githubusercontent.com/13350158/167637049-cab03ada-544f-4d8f-822f-f3d102a57ab6.png)

to see vel about x-coord
I write a python script to read and plot data from QtIdealTraj.dat
the result like that:

![image](https://user-images.githubusercontent.com/13350158/167636840-17b97b1a-ea6d-45f6-b12a-17418b0c6dad.png)

**we can see vel jump very seriously ,so Can you improve it and solve the problem，**
the python file:

`import numpy as np
import matplotlib.pyplot as plt
jnt_vel_file_name = 'QtIdealTraj.dat'
jnt_num = 5
cnt= []
pos_x = []
pos_y = []
pos_z = []
vel_x = []
acc_x = []
with open(jnt_vel_file_name, 'r') as f:#1
    lines = f.readlines()#2
    for line in lines:#3
        value = [float(s) for s in line.split()]#4
        cnt.append(value[0])#5
        pos_x.append(value[1])
        if jnt_num >1 :
          pos_y.append(value[2])
        if jnt_num >2 :
          pos_z.append(value[3])
        if jnt_num >3 :
          vel_x.append(value[4])
        if jnt_num >4 :
          acc_x.append(value[5]) 
         
if jnt_num >0 :
  plt.plot(cnt,pos_x,'ro',label='pos_x')   
if jnt_num >1 :
  plt.plot(cnt, pos_y,'bo',label='pos_y')
if jnt_num >2 :
   plt.plot(cnt, pos_z,'go',label='pos_z')
if jnt_num >3 :
   plt.plot(cnt, vel_x,'r+',label='vel_x')
plt.xlabel('cnt')  
plt.ylabel('pram')
plt.legend()
plt.show()`

**Comment by severin-lemaignan** [comment]
hi,
Unfortunately, I am not working on this code since about ~10 years, and it is not maintained anymore. If it would be useful to you, I recommend you to fork the repository, and start working on fixing the issues you encounter.

**Comment by dbdxnuliba** [comment]
ok ,thanks
